# Generated by Django 2.2.14 on 2022-05-26 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190630_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='max_quantity',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('C', 'Čelenka'), ('T', 'Tričko')], max_length=1),
        ),
    ]
