# Generated by Django 2.2.14 on 2022-05-27 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20220527_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('nic', 'non'), ('Akce', 'primary'), ('Sleva', 'secondary'), ('Výprodej', 'danger')], max_length=1),
        ),
    ]
