# Generated by Django 2.2.14 on 2022-05-27 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20220527_0936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='max_quantity',
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('C', 'Čelenky'), ('T', 'Trička')], max_length=1),
        ),
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('N', 'nic'), ('D', 'Sleva')], max_length=1),
        ),
    ]
