# Generated by Django 2.2.14 on 2022-06-01 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20220601_2130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='street_address',
            new_name='street_adress',
        ),
    ]
