# Generated by Django 2.2.14 on 2022-06-01 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20220601_2133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='street_adress',
            new_name='street_address',
        ),
    ]
